/**
 * Rules for field checking
 */
exports.RULES = {
    NO_RESTRICTIONS: 0,
    NOT_UNDEFINED: 1,
    NOT_NULL: 2,
    ALLOWED_TRUE: 3,
    ALLOWED_FALSE: 4,
    ALLOWED_NULL: 5,
    ALLOWED_UNDEFINED: 6,
    ALLOWED_NUMBER: 7,
    ALLOWED_OBJECT: 8,
    ALLOWED_STRING: 9,
    ALLOWED_ARRAY: 10,
    ALLOWED_FUNCTION: 11,
    ALLOWED_DATE: 12,
    ALLOWED_FILE: 13,
};